### ISSUE TITLE
Define Scope of Reproducibility

### ISSUE THREAD

**Issue by minaremeli** [minaremeli/MOON#3]
## Task scope
**We recommend you focus on the central claim of the paper.** For example, if a paper introduces a new RL learning algorithm that performs better in sparse-reward environments, verify that you can re-implement the algorithm, run it on the same benchmarks and get results that are close to those in the original paper (exact reproducibility is in most cases very difficult due to minor implementation details). You do not need to reproduce all experiments in your selected paper, but only those that you feel are sufficient for you to verify the validity of the central claim. 

More information on the task [here](https://paperswithcode.com/rc2021/task).

## ToDo's
- [x] Briefly define the claim of the paper that you intend to tackle in this report.
- [x] Choose experiments to reproduce.
- [x] Review possible extension of the paper w/ additional experiments. (optional)
